### Get all quests
https://{{host}}
Accept: application/hal+json
Authorization: {{basic-auth-admin}}
ALPN: h2

### Search with ID
https://{{host}}/randomuser
Accept: application/hal+json
Authorization: {{basic-auth}}
ALPN: h2

###
# ALPN: h2, http%2F1.1