version: "3.4"

services:
  data-backend:
    restart: always
    image: odyquest-data-backend
    container_name: data-backend
    environment:
      ODYQUEST_CORS_ORIGIN: "http://localhost:4200"
      ODYQUEST_MONGODB_URL: "mongodb://data-mongodb:27017/production"
      ODYQUEST_API_PORT: "8444"
      ODYQUEST_USE_AUTH: "false"
      ODYQUEST_AUTH_ISSUER_BASE_URL: "https://cms.schnitzeljagd.landesmuseum.de/auth/realms/master"
      ODYQUEST_AUTH_JWKS_URL: "https://cms.schnitzeljagd.landesmuseum.de/auth/realms/master/protocol/openid-connect/certs"
    networks:
      - default
      - data-database
    ports:
      - 8444:8444
  data-mongodb:
    image: mongo:latest
    container_name: data-mongodb
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - data-database


volumes:
  mongodb_data_container:

networks:
  data-database:

