server.port: 8444

# https://github.com/sdeleuze/spring-kotlin-functional/blob/boot/src/main/resources/application.properties
context.initializer.classes: x.museum.chase.BeansInitializer


spring:
  application.name: chase
  cloud.stream.kafka.binder.configuration:
    - listeners: PLAINTEXT://localhost:9092,SSL://localhost:9093
  data.mongodb:
    authentication-database: admin
    auto-index-creation: false
    #port: 27017
    repositories.type: none
    database: museumX
    # for docker use "mongo", for local db use "localhost" as host
    host: localhost
    password: 'Admin123'
    #replicaSetName: replicaSet
    username: admin
    uuid-representation: standard


server:
  compression:
    enabled: true
    mime-types: application/hal+json
    min-response-size: 2KB
  error.whitelabel.enabled: false
  http2.enabled: true
  ssl:
    enabled: false
#    enabled-protocols: TLSv1.3,TLSv1.2
#    trust-store: classpath:truststore.p12
#    trust-store-password: Admin123
#    trust-store-type: PKCS12
#    key-alias: microservice
#    key-password: Admin123
#    key-store: classpath:keystore.p12
#    key-store-password: Admin123
#    key-store-type: PKCS12

  shutdown: graceful

management:
  endpoints.web.exposure.include: "*"
  endpoint:
    health.enabled: true
    shutdown.enabled: true
