### Uebersicht
https://{{host}}
Authorization: {{basic-auth}}

### Alle Routen auflisten
https://{{host}}/gateway/routes
Authorization: {{basic-auth}}

### Features
https://{{host}}/features
Authorization: {{basic-auth}}

### Consul
https://{{host}}/consul
Authorization: {{basic-auth}}

### Laeuft die Service-Registry?
https://{{host}}/service-registry
Authorization: {{basic-auth}}

### "Health" der einzelnen Services
https://{{host}}/health
Authorization: {{basic-auth}}

### Shutdown
POST https://{{host}}/shutdown
Authorization: {{basic-auth}}
Content-Type: application/json

###
