### Löschen mit vorhandener Kunde-ID
DELETE https://{{host}}/00000000-0000-0000-0000-000000000004
Authorization: {{basic-auth}}

### Löschen mit vorhandener Email
DELETE https://{{host}}?email=phi@acme.cn
Authorization: {{basic-auth}}

### Löschen mit vorhandener Kunde-ID, ohne Authentifizierung
DELETE https://{{host}}/00000000-0000-0000-0000-000000000004

### Löschen mit vorhandener Email, ohne Authentifizierung
DELETE https://{{host}}?email=phi@acme.cn

###
